version: "2"
services:

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - "rutorrent"
      - "plex"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./rutorrent/config:/config
      - ./rutorrent/downloads:/downloads
    ports:
      - 8080:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    expose:
      - 32400
      - 33400
    volumes:
      - ./plex/library:/config
      - ./plex/transcode:/transcode
      - ${PATH_MEDIA}:/media
    restart: unless-stopped
