version: "2"
services:
  rutorrent:
    image: linuxserver/rutorrent
    container_name: rutorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./rutorrent/config:/config
      - ./rutorrent/downloads:/downloads
    ports:
      - 80:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    expose:
      - 32400
      - 33400
    volumes:
      - ./plex/library:/config
      - ./plex/transcode:/transcode
      - ${PATH_MEDIA}:/media
    network_mode: "host"
    restart: unless-stopped
